addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.6.2")
addSbtPlugin("rocks.earlyeffect" % "sbt-dynver-ci" % "0.2.2")
addSbtPlugin("com.github.sbt"    % "sbt-pgp"       % "2.3.1")
addSbtPlugin("rocks.earlyeffect" % "sbt-specular"  % "0.12.1")
addSbtPlugin("rocks.earlyeffect" % "sbt-zipx"      % "0.6.2")
addSbtPlugin("rocks.earlyeffect" % "sbt-chekhov"   % "0.0.4")
