// Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate.
addSbtPlugin("rocks.earlyeffect" % "sbt-zipx" % "0.9.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")
addSbtPlugin("rocks.earlyeffect" % "sbt-dynver-ci" % "0.2.3")
addSbtPlugin("rocks.earlyeffect" % "sbt-specular" % "0.14.1")
addSbtPlugin("rocks.earlyeffect" % "sbt-chekhov" % "0.0.5")
