MyVersions.settings
version        := "1.0.0-ci"
zipxCacheEpoch := CacheEpoch.Fixed("1.0.0-ci")

enablePlugins(ScalaJSPlugin)

scalaJSUseMainModuleInitializer := true
scalaJSLinkerConfig ~= { _.withModuleKind(ModuleKind.ESModule) }

spliceLibs += Splice
  .lib("foo", "1.0.0", "foo.js")
  .sha256("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")

ThisBuild / splicePinLookup     := SplicePins.constLookup("1.0.1")
ThisBuild / splicePinResolveSha := SplicePins.constSha("bb" * 32)

lazy val root = (project in file("."))
  .settings(publish / skip := true)

val assertPlugins = taskKey[Unit]("assert generated plugins.sbt emits splice without catalog Plugin vals")
assertPlugins := {
  val plugins = IO.read((LocalRootProject / baseDirectory).value / "project" / "plugins.sbt")
  assert(plugins.startsWith("// Generated by zipx."), "plugins.sbt should start with the generated header")
  assert(
    plugins.contains("""addSbtPlugin("rocks.earlyeffect" % "sbt-zipx" %"""),
    "plugins.sbt should emit loaded sbt-zipx first",
  )
  assert(
    plugins.contains("""addSbtPlugin("rocks.earlyeffect" % "sbt-splice" %"""),
    "plugins.sbt should self-emit sbt-splice",
  )
  assert(
    plugins.contains("""addSbtPlugin("rocks.earlyeffect" % "sbt-splice-zipx" %"""),
    "plugins.sbt should self-emit sbt-splice-zipx",
  )
  assert(
    plugins.contains("""addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")"""),
    "plugins.sbt should emit catalog plugins",
  )
  assert(plugins.indexOf("sbt-zipx") < plugins.indexOf("sbt-splice"), "sbt-zipx should be before sbt-splice")
  assert(
    plugins.indexOf("sbt-splice\"") < plugins.indexOf("sbt-splice-zipx"),
    "sbt-splice should be before sbt-splice-zipx",
  )
  assert(
    plugins.indexOf("sbt-splice-zipx") < plugins.indexOf("sbt-scalafmt"),
    "self-emitted plugins should be before catalog plugins",
  )
}

val assertPinFeeds = taskKey[Unit]("assert pin-check job and companion, no snapshot")
assertPinFeeds := {
  val root  = (LocalRootProject / baseDirectory).value
  val ci    = IO.read(root / ".github" / "workflows" / "ci.yml")
  val check = IO.read(root / ".github" / "workflows" / "zipx-pin-check.yml")
  assert(ci.contains("pin-check:"), "ci.yml should contain the pin-check job")
  assert(ci.contains("zipxPinCheckPr") || ci.contains("zipxPinCheckPr'"), "pin-check should run zipxPinCheckPr")
  assert(check.contains("sbt zipxPinCheck"), "pin-check companion should run zipxPinCheck")
  assert(
    !(root / ".github" / "workflows" / "zipx-pin-snapshot.yml").exists,
    "snapshot companion should be absent when submitSnapshot is false",
  )
}

val assertPinUpdate = taskKey[Unit]("assert zipxPinUpdate yes rewrote version and sha256")
assertPinUpdate := {
  val text   = IO.read((LocalRootProject / baseDirectory).value / "build.sbt")
  val oldSha = "aa" * 32
  val newSha = "bb" * 32
  assert(text.contains(""".lib("foo", "1.0.1", "foo.js")"""), s"expected bumped foo pin, got:\n$text")
  assert(text.contains(newSha), s"expected new sha256, got:\n$text")
  assert(!text.contains(oldSha), s"old sha256 should be gone, got:\n$text")
}
